# Generated by Django 3.0.7 on 2020-07-12 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.thesis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('max_groups_num', models.PositiveSmallIntegerField(default=5)),
                ('min_groups_num', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('department', models.CharField(choices=[('CSE', 'Cse'), ('EEE', 'Eee'), ('ETE', 'Ete'), ('PHM', 'Phm')], max_length=3)),
                ('md5hash', models.CharField(max_length=10, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.Batch')),
                ('external', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='external_studentgroups', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentgroups', to='thesis.ResearchField')),
                ('internal', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='internal_studentgroups', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='studentgroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_viewed', models.BooleanField(default=False)),
                ('studentgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.StudentGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('Proposal', 'Proposal'), ('Pre-Defense Report', 'Pre Defense'), ('Defense Report', 'Defense')], max_length=24)),
                ('file', models.FileField(upload_to=website.thesis.models.generate_upload_location)),
                ('is_accepted', models.BooleanField(default=False)),
                ('studentgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='thesis.StudentGroup')),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studentgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='thesis.StudentGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
