# Generated by Django 2.0.5 on 2018-05-23 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('md5hash', models.CharField(max_length=33, null=True)),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentgroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
