# Generated by Django 3.0.7 on 2020-07-24 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0003_auto_20200715_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='first_choice',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_studentgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='second_choice',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_studentgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='third_choice',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_choice_studentgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='external',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_external': True, 'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='external_studentgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
