# Generated by Django 2.0.5 on 2018-06-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-upload_time']},
        ),
    ]
