# Generated by Django 3.0.7 on 2020-07-25 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20200724_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='external_mark_percentage',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='batch',
            name='internal_mark_percentage',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='batch',
            name='supervisor_mark_percentage',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
