# Generated by Django 2.0.5 on 2018-06-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='studentgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='thesis.StudentGroup'),
        ),
    ]
