# Generated by Django 3.0.7 on 2020-07-25 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20200725_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='max_students_per_group',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
