# Generated by Django 2.0.5 on 2018-06-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_auto_20180606_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
