# Generated by Django 3.0.7 on 2020-09-08 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0006_batch_max_students_per_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('suggestions', models.TextField()),
                ('topic_discussed', models.TextField()),
                ('work_done_after_last_meeting', models.TextField()),
                ('meeting_type', models.CharField(choices=[('On-Site', 'On Site'), ('Online', 'Online')], max_length=7)),
                ('studentgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='thesis.StudentGroup')),
                ('students_present', models.ManyToManyField(blank=True, related_name='logbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'logbooks',
            },
        ),
    ]
