# Generated by Django 3.0.7 on 2020-09-08 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0007_logbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='students_present',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='logbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
