# Generated by Django 2.0.5 on 2018-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_auto_20180606_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
