# Generated by Django 3.0.7 on 2020-10-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0008_auto_20200909_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='studentgroups', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
