# Generated by Django 3.0.7 on 2020-10-03 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0009_auto_20201003_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='internal',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='internal_studentgroups', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
    ]
