# Generated by Django 3.0.7 on 2020-10-04 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_auto_20201004_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='student_list',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('([A-Z]{1,2}\\d{6},?\\s?)+')]),
        ),
    ]
