# Generated by Django 2.1 on 2018-09-26 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_auto_20180925_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchfield',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': True}, null=True, related_name='fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
