# Generated by Django 2.1 on 2018-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0012_auto_20180926_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
