# Generated by Django 3.0.7 on 2020-07-11 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesis', '0013_studentgroup_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('max_groups_num', models.PositiveSmallIntegerField(default=5)),
                ('min_groups_num', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='external',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='external_studentgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='internal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='internal_studentgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='studentgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.Batch'),
        ),
    ]
