# Generated by Django 3.0.7 on 2020-07-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0015_auto_20200711_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Proposal', 'Proposal'), ('Pre-Defense Report', 'Pre Defense'), ('Defense Report', 'Defense')], default='PROPOSAL', max_length=24),
            preserve_default=False,
        ),
    ]
