# Generated by Django 3.0.7 on 2020-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200715_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Designates whether this teacher should be treated as an external teacher.', verbose_name='external teacher status'),
        ),
    ]
