# Generated by Django 3.0.7 on 2020-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200724_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
