# Generated by Django 2.1 on 2018-09-28 13:49

from django.db import migrations, models
import website.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180928_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv_document',
            field=models.FileField(blank=True, null=True, upload_to=website.registration.models.generate_cv_upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as teacher.', verbose_name='teacher status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=website.registration.models.generate_propic_upload_location),
        ),
    ]
