# Generated by Django 3.0.7 on 2020-07-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20200725_1705'),
        ('registration', '0006_auto_20200725_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as admin.', verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='thesis.StudentGroup'),
        ),
    ]
