# Generated by Django 2.1 on 2018-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180928_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='qualification'),
        ),
    ]
