# Generated by Django 2.1 on 2018-09-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_user_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='designation'),
        ),
    ]
