# Generated by Django 3.0.7 on 2020-07-31 08:28

from django.db import migrations


def update_marks_to_include_result(apps, schema_editor):
    Mark = apps.get_model('registration', 'Mark')
    for mark in Mark.objects.all():
        try:
            if mark.student.result:
                mark.result = mark.student.result
                mark.save()
        except Exception as e:
            print(f'Could not Update Mark: {mark.id}')


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0009_mark_result'),
    ]

    operations = [
        migrations.RunPython(update_marks_to_include_result)
    ]
