# Generated by Django 3.0.7 on 2020-07-11 08:36

from django.db import migrations, models
import website.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.user',),
            managers=[
                ('objects', website.registration.models.CutomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.user',),
            managers=[
                ('objects', website.registration.models.CutomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CSE', 'Cse'), ('EEE', 'Eee'), ('ETE', 'Ete'), ('PHM', 'Phm')], default='CSE', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
