# Generated by Django 3.0.7 on 2020-07-11 09:00

from django.db import migrations, models
import website.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20200711_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.user',),
            managers=[
                ('objects', website.registration.models.CutomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as student.', verbose_name='student status'),
        ),
    ]
