# Generated by Django 3.0.7 on 2020-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200711_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as student.', verbose_name='student status'),
        ),
    ]
