# Generated by Django 3.0.7 on 2020-08-03 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200803_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
