# Generated by Django 3.0.7 on 2020-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20200803_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_registration', models.BooleanField(default=True)),
            ],
        ),
    ]
