# Generated by Django 3.0.7 on 2020-09-07 16:53

from django.db import migrations


def create_default_setting(apps, schema_editor):
    WebsiteSettings = apps.get_model('registration', 'WebsiteSettings')
    WebsiteSettings.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_websitesettings'),
    ]

    operations = [
        migrations.RunPython(create_default_setting),
    ]
