# Generated by Django 3.0.7 on 2020-09-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20200907_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'website setting'},
        ),
    ]
