# Generated by Django 3.0.8 on 2020-07-05 19:05

from django.db import migrations, models
import groups.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('max_groups_limit', models.PositiveSmallIntegerField(default=5)),
                ('min_groups_limit', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_batch',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=groups.utils.generate_upload_location)),
                ('is_accepted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Proposal Report', 'Proposal'), ('Pre-Defense Report', 'Pre Defense Report'), ('Defense Report', 'Defense Report')], max_length=20)),
            ],
            options={
                'db_table': 'tbl_document',
                'ordering': ['-created_at'],
                'default_related_name': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('unique_id', models.CharField(blank=True, max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_group',
                'ordering': ['created_at'],
                'default_related_name': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tbl_mark',
                'default_related_name': 'marks',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_message',
                'ordering': ['-created_at'],
                'default_related_name': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'db_table': 'tbl_message_channel',
                'default_related_name': 'message_channels',
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tbl_research_field',
                'ordering': ['name'],
                'default_related_name': 'research_fields',
            },
        ),
    ]
