# Generated by Django 3.0.8 on 2020-07-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfield',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='fields', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='messagechannel',
            name='users',
            field=models.ManyToManyField(related_name='message_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.MessageChannel'),
        ),
        migrations.AddField(
            model_name='mark',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='mark',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='users.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.Batch'),
        ),
        migrations.AddField(
            model_name='group',
            name='external',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_groups', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='groups.ResearchField'),
        ),
        migrations.AddField(
            model_name='group',
            name='internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_groups', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='message_channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='groups.MessageChannel'),
        ),
        migrations.AddField(
            model_name='group',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_groups', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_groups', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'graded_by')},
        ),
    ]
